[workspace]
members = [
    "crates/lewitt-app",
    "crates/lewitt-backend-linux",
    "crates/lewitt-backend-windows",
    "crates/lewitt-core",
    "crates/lewittctl",
]
resolver = "3"
default-members = ["crates/lewitt-app"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.88"

[workspace.dependencies]
crossbeam-channel = "0.5"
lewitt-core = { path = "crates/lewitt-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
