app.title = Stream 4x5 Control Panel
app.subtitle = Hardware status from the platform audio driver
app.disclaimer = Unofficial compatibility project; not affiliated with Lewitt GmbH.
tray.show = Show
tray.reconnect = Reconnect
tray.status = Status
tray.quit = Quit
action.refresh = Refresh
status.no_device = No Stream 4x5 detected
status.discovering = Looking for Stream 4x5…
status.connecting = Connecting read-only…
status.connected = Connected
status.error = Driver read failed
status.read_only = Firmware is not approved for writes
status.read_only_detail = Live hardware values are available; controls remain locked until write captures are verified.
status.meters_pending = Driver RMS reads are not enabled in this build.
status.fixed_input_detail = Input 3/4 has no hardware gain or mute control.
notice.controller_failed = A background component stopped. See the local log for details.
notice.driver_missing = The Lewitt driver or vendor API is unavailable. Install or repair Lewitt Control Center.
notice.permission_denied = Stream 4x5 access was denied. Check the device permissions.
notice.device_busy = Stream 4x5 is busy. Close other control software and reconnect.
notice.device_disconnected = Stream 4x5 was disconnected.
notice.device_read_failed = Device data could not be read. See the local log for details.
notice.invalid_value = The requested control value was rejected.
notice.operation_unavailable = This operation is not available for the connected device.
notice.tray_failed = The system tray is unavailable; the main window remains usable.
notice.tray_unsupported = The system tray is unsupported on this platform.
notice.control_center_conflict = Lewitt Control Center is using the device; this application remains read-only.
section.inputs = Hardware Inputs
section.outputs = Hardware Outputs
section.device = Device
channel.input_1 = Input 1
channel.input_2 = Input 2
channel.input_3_4 = Input 3/4
channel.output_1_2 = Output 1/2
channel.output_3_4 = Output 3/4
channel.output_5_6 = Output 5/6
control.gain = Gain
control.output_mute = Output mute
control.phantom = 48V
control.high_pass = 80 Hz
control.phase = Phase Ø
state.on = On
state.off = Off
state.fixed = Fixed
state.muted = Muted
device.firmware = Firmware
device.sample_rate = Sample rate
device.clock = Clock
device.asio_buffer = ASIO buffer
device.internal = Internal
device.external = External
device.unavailable = —
onboarding.autostart = Start automatically in the background after sign-in
onboarding.confirm = Confirm
