app.title = Stream 4x5 控制面板
app.subtitle = 通过平台音频驱动读取硬件状态
app.disclaimer = 非官方兼容项目，与 Lewitt GmbH 无隶属或合作关系。
tray.show = 显示
tray.reconnect = 重新连接
tray.status = 状态
tray.quit = 退出
action.refresh = 刷新
status.no_device = 未检测到 Stream 4x5
status.discovering = 正在查找 Stream 4x5…
status.connecting = 正在连接…
status.connected = 已连接
status.error = 驱动读取失败
status.read_only = 当前固件尚未完全批准写入
status.read_only_detail = 已显示硬件实时值；部分控件保持锁定。
status.hardware_writes_detail = 已启用输入 1/2 前级增益、48V、80 Hz 高通、相位、三组输出增益及硬件输出静音写入；其他控件仍保持只读。
status.meters_pending = 此版本尚未启用驱动 RMS 读取。
status.fixed_input_detail = 输入 3/4 没有硬件增益或静音控制。
notice.controller_failed = 后台组件已停止，详细信息请查看本地日志。
notice.driver_missing = Lewitt 驱动或厂商 API 不可用，请安装或修复 Lewitt Control Center。
notice.permission_denied = Stream 4x5 访问被拒绝，请检查设备权限。
notice.device_busy = Stream 4x5 正被占用，请关闭其他控制软件后重新连接。
notice.device_disconnected = Stream 4x5 已断开连接。
notice.device_read_failed = 无法读取设备数据，详细信息请查看本地日志。
notice.invalid_value = 请求的控制值被设备拒绝。
notice.operation_unavailable = 当前设备不支持此操作。
notice.tray_failed = 系统托盘不可用，主窗口仍可继续使用。
notice.tray_unsupported = 当前平台不支持系统托盘。
notice.control_center_conflict = Lewitt Control Center 正在使用设备，本应用将保持只读。
section.inputs = 硬件输入
section.outputs = 硬件输出
section.device = 设备
channel.input_1 = 输入 1
channel.input_2 = 输入 2
channel.input_3_4 = 输入 3/4
channel.output_1_2 = 输出 1/2
channel.output_3_4 = 输出 3/4
channel.output_5_6 = 输出 5/6
control.gain = 增益
control.output_mute = 输出静音
control.phantom = 48V
control.high_pass = 低切(80 Hz)
control.phase = 相位 Ø
state.on = 开
state.off = 关
state.fixed = 固定
state.muted = 静音
device.firmware = 固件
device.sample_rate = 采样率
device.clock = 时钟
device.asio_buffer = ASIO 缓冲区
device.internal = 内部
device.external = 外部
device.unavailable = —
onboarding.autostart = 登录后在后台自动启动
onboarding.confirm = 确认
